### ISSUE TITLE
テストプレイ後の検討会

### ISSUE THREAD

**Issue by tex2e** [13J-Programmers/5J-game#10]
## Outline

テストプレイの感想と、今後のゲームの改善点など

- プレイ時間は2:30~3:00
- 初見は失敗する（相方がワクチン開発に成功しないなど）
- ワクチンまでの数を20に下げたところ、詰まらずに（詰む回数が減って）クリアした

## Tasks

- [x] ゲームの説明（操作方法、各プレイヤーの役割、最終的な目標）
    - 同じ色のタイルを合わせるイラスト
    - 何個抗体を合わせるとワクチン・ビンになるのかを明記するイラスト（ただし、具体的な個数はゲームレベルで変わるので、別のレイヤーで表示させる）
- [x] モード選択によってワクチンまでに必要な個数を補足する
- [x] チュートリアルのスキップ（キーボード：スペースキー、ゲームパッド：スタートボタン）
- [x] Result（上から下ろすパネル）。表示内容は完成したワクチン・ビンの数・時間
- [x] Gamepadだけで一連の流れを行えるように
- [x] BGM
- [x] モードの選択
    - (a) ボタンで normal mode
    - (x) ボタンで hard mode (ワクチン・ビンまでの個数増加、確率変動など)
- [x] 下のprogress barの進捗の各フェーズ間の中間値の表示
    - before: wait 30sec => nextStage => animation in 1000ms
    - after: wait 0sec => nextStage => animation in 30000ms
- [x] 完成したワクチンの↷なエフェクト
- [x] 作ったビンの数とその効果（一番下が0%、一番上が100%）
    - 0~100%の文字を表示して、100%になったら、バックグランドの色を付ける
- [ ] 自分の色のワクチンが完成したあとに、「ビンを作って友達を助けよう」等のテロップがあるとわかりやすい
- [ ] ラッキータイル（レインボータイル）

## Additional Tasks

- [x] game clear時にprogress-bar のアニメーションを止める
- [x] ゲームタイトルで後ろのパズル画面と重ならないようにする（チュートリアルに入る前にガジェットたちが真ん中に集まるアニメーション）
- [x] 逆に、ゲームリザルト画面では後ろのパズル画面と重ならないように、アニメーションでガジェットたちを画面外に動かす
- [x] リザルト：人類勝利/人類滅亡、経過フェーズとその説明（4なら人-人感染）
- [x] ワクチンの完成時の下のワクチンのアニメーション(blink)
- [ ] progress barのphase6をdangerなマークする
    - 2-3-4-5-6-X（phase1を無くす）Xの段階に到達した時点でゲームオーバ
    - phase1に関しては動物インフルエンザであるため、人類を救うという目的に乖離しているとの指摘がある（ちなみに、ゲームパッドによる複数回のテストプレイの結果よりクリアまで最速で30秒）
    - phaseに関しては現在WHOが提言している各phaseの状態と相違があるので、整合性を取るためにphaseという表現を撤回する必要性もある
- [ ] チュートリアルでプレイヤにパズルをやらせる（抗体の数が10になるまでやらせるなど）
- [ ] CPU役でゲームをするモードの追加

**Comment by KoiShin** [comment]
例年のように、スコアを数字で表示したほうがわかりやすいのではないか(ワクチン、ビンの数、残り時間による)

**Comment by tex2e** [comment]
スコアというニュアンスで感染者数という案が出てた（具体的な式は知らないけど）

**Comment by nobuyo** [comment]
> スコアというニュアンスで感染者数

これは感染を抑え込むという設定とすり合わせが必要そう

**Comment by uiby** [comment]
ゲームの目的がワクチンを4つ完成させることなら、感染者数は演出の範囲内で良さそうだと思う。
phaseが進むごとに感染者を増やして危機感を煽る役割とか。
プレイ後の評価をつけるならリザルト項目をスコア(数字)に換算した方が無難そう。

**Comment by KoiShin** [comment]
確かに。
それと、PHASE6のところだけdangerなマークにしたほうがわかりやすいのではないかという案が出た。

**Comment by tex2e** [comment]
もしプレイを評価するという意味でスコアが必要なら、
- ワクチン完成までに動かした回数
- 何回リトライしたか
- 何回タイル同士がマージされて、その値は累積でどれくらいなのか

という指標も必要だと思う。

**Comment by tex2e** [comment]
身内で遊ぶ分にはスコアがあると比較ができて盛り上がるけど、1回しか遊ばない外のお客さんにとってはスコアはあまり重要ではないと思ってる。

PHASE6のところだけdangerなマークにするのはいいと思うけど、CSS次第

**Comment by KoiShin** [comment]
- スコア画面の感染レベルとバックグラウンドの感染が広がる様子の整合性がとれていない(人類への感染拡大を防ぐゲームのはずなのにPHASE1の状態でクリアするとそもそも人への感染がないウイルスしか存在しない状態でゲームクリアとなり、多少の矛盾がある)。
- ゲーム開始時カウントダウンの文字が小さい
